version: "3"

networks: 
    laravel:
        driver: bridge

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_vuexy_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        env_file:
            - .docker.env
        volumes: 
            - ./src:/var/www/app
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    nginx:
        image: nginx:1.17
        container_name: laravel_vuexy_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: laravel_vuexy_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        container_name: laravel_vuexy_phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            UPLOAD_LIMIT: 1G
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        links:
            - mysql
        networks:
            - laravel
